// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnhnQpng4GMJn4ugFNl-_u4c_0al94ks4',
    appId: '1:1040608233805:web:1b39d1dbc104fa4b260f04',
    messagingSenderId: '1040608233805',
    projectId: 'minggu2-8436c',
    authDomain: 'minggu2-8436c.firebaseapp.com',
    storageBucket: 'minggu2-8436c.firebasestorage.app',
    measurementId: 'G-JRJ2K1BHSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWLYisB6-OahfQ3URRrNX6_AFru2La_I',
    appId: '1:1040608233805:android:039664027c183cfc260f04',
    messagingSenderId: '1040608233805',
    projectId: 'minggu2-8436c',
    storageBucket: 'minggu2-8436c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGIzOq15lJ-4uh1oGteCCf0Vgnz7oepM',
    appId: '1:1040608233805:ios:0f46b77426ddaa6b260f04',
    messagingSenderId: '1040608233805',
    projectId: 'minggu2-8436c',
    storageBucket: 'minggu2-8436c.firebasestorage.app',
    iosBundleId: 'com.example.minggu2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgGIzOq15lJ-4uh1oGteCCf0Vgnz7oepM',
    appId: '1:1040608233805:ios:0f46b77426ddaa6b260f04',
    messagingSenderId: '1040608233805',
    projectId: 'minggu2-8436c',
    storageBucket: 'minggu2-8436c.firebasestorage.app',
    iosBundleId: 'com.example.minggu2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnhnQpng4GMJn4ugFNl-_u4c_0al94ks4',
    appId: '1:1040608233805:web:8ca31959ac4f998b260f04',
    messagingSenderId: '1040608233805',
    projectId: 'minggu2-8436c',
    authDomain: 'minggu2-8436c.firebaseapp.com',
    storageBucket: 'minggu2-8436c.firebasestorage.app',
    measurementId: 'G-NVT6NR0XL5',
  );
}
