// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tzUdCHvoiTldrg1VsWxX9bDsoEJN9wU',
    appId: '1:1029626046967:web:bdde0ff71c52bb6ba366f2',
    messagingSenderId: '1029626046967',
    projectId: 'myapp-cf3d4',
    authDomain: 'myapp-cf3d4.firebaseapp.com',
    storageBucket: 'myapp-cf3d4.firebasestorage.app',
    measurementId: 'G-GNP6PSBN5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAth45JMzLS2c2Wb6xv4kqGHsouflYayys',
    appId: '1:1029626046967:android:978ad2ecc8d5eaf0a366f2',
    messagingSenderId: '1029626046967',
    projectId: 'myapp-cf3d4',
    storageBucket: 'myapp-cf3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_tf6gNd7Wt4NE2XvW9UqwRtXbJ5uJr4k',
    appId: '1:1029626046967:ios:e09d4eb14f072cd1a366f2',
    messagingSenderId: '1029626046967',
    projectId: 'myapp-cf3d4',
    storageBucket: 'myapp-cf3d4.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_tf6gNd7Wt4NE2XvW9UqwRtXbJ5uJr4k',
    appId: '1:1029626046967:ios:e09d4eb14f072cd1a366f2',
    messagingSenderId: '1029626046967',
    projectId: 'myapp-cf3d4',
    storageBucket: 'myapp-cf3d4.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8tzUdCHvoiTldrg1VsWxX9bDsoEJN9wU',
    appId: '1:1029626046967:web:342bef28c2fba944a366f2',
    messagingSenderId: '1029626046967',
    projectId: 'myapp-cf3d4',
    authDomain: 'myapp-cf3d4.firebaseapp.com',
    storageBucket: 'myapp-cf3d4.firebasestorage.app',
    measurementId: 'G-TLPTNE5XEV',
  );
}
